name: troubleshooter
favicon: null
layout_spectrum: 0.9863259303383529
typography_spectrum: 0.2545502388384193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#7c7d80'
    - '#c5c5c7'
    - '#3b3b3b'
  brandStrength: 0.7559187009464949
  lightness: 0.039902363205328584
  saturation: 0.6362212721724063
  rhythmicContrast: 0.9712150811683387
purpose: []
